# Tensorflow build Neuro Net Work

![](https://i.imgur.com/XTIg6qt.png)

## <font color='dark'>Import</font>

In [17]:
import tensorflow as tf
import numpy as np

## <font color='dark'>Simple exercise : using array</font>

首先我們來實作一個 y1 = relu(X * w + b1) 的過程<br>
relu 的算法是只要小於 0 ，就歸 0; 大於 0, 則等於它原本的值

In [3]:
x = tf.Variable([[0.4,0.2,0.4]])
w = tf.Variable([[-0.5,-0.2],[-0.3,0.4],[-0.5,0.2]])
b = tf.Variable([[0.1,0.2]])

xwb = tf.matmul(x,w)+b
y = tf.nn.relu(xwb)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('X*W+b : ',sess.run(xwb))
    print('y : ',sess.run(y))

X*W+b :  [[-0.36000004  0.28      ]]
y :  [[0.   0.28]]


接下來我們來實作一個 y1 = sigmoid(X * w + b1) 的過程

In [4]:
x = tf.Variable([[0.4,0.2,0.4]])
w = tf.Variable([[-0.5,-0.2],[-0.3,0.4],[-0.5,0.2]])
b = tf.Variable([[0.1,0.2]])

xwb = tf.matmul(x,w)+b
y = tf.nn.sigmoid(xwb)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('X*W+b : ',sess.run(xwb))
    print('y : ',sess.run(y))

X*W+b :  [[-0.36000004  0.28      ]]
y :  [[0.41095954 0.5695462 ]]


在之前我們已經學過 Deep learning 的模型是以 Back propagation 的方式來訓練。<br>
因此一開始我們必須先給模型一個亂數初始化的 **權重(weight)** 和 **偏差(bias)**

In [14]:
x = tf.Variable([[0.4,0.2,0.4]])
w = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
y = tf.nn.relu(tf.matmul(x,w)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('x : ',sess.run(x))
    print('b : ',sess.run(b))
    print('w : \n',sess.run(w))
    print('\ny : ',sess.run(y))

x :  [[0.4 0.2 0.4]]
b :  [[-1.2172332  0.9481905]]
w : 
 [[-0.36710495 -0.61733115]
 [ 1.7086805   0.447966  ]
 [-1.8447334  -1.9523746 ]]

y :  [[0.        0.0099014]]


In [16]:
# 這邊提供一個更簡便的寫法, 變數 run 一次 sess 就好

x = tf.Variable([[0.4,0.2,0.4]])
w = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
y = tf.nn.relu(tf.matmul(x,w)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (b,w,y) = sess.run((b,w,y))
    print('b : ',b)
    print('w : \n',w)
    print('\ny : ',y)

b :  [[-1.3222859  1.2233078]]
w : 
 [[ 3.0846481   1.2570065 ]
 [-0.27301225  0.8609854 ]
 [-0.29107988 -1.1276252 ]]

y :  [[0.        1.4472575]]


### Using placeholder

In [19]:
x = tf.placeholder("float",[None,3])
w = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
y = tf.nn.relu(tf.matmul(x,w)+b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    x_array = np.array([[0.4,0.2,0.4]])
    (x,w,b,y) = sess.run((x,w,b,y),feed_dict={x:x_array})
    
    print('x : ',x)
    print('b : ',b)
    print('w : \n',w)
    print('\ny : ',y)

x :  [[0.4 0.2 0.4]]
b :  [[-0.8287806  1.9377056]]
w : 
 [[ 1.259302   -0.026501  ]
 [-1.1970146   0.82814115]
 [ 0.07466117  0.70939994]]

y :  [[0.        2.3764935]]


In [22]:
x = tf.placeholder("float",[None,3])
w = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
y = tf.nn.relu(tf.matmul(x,w)+b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    x_array = np.array([[0.4,0.2,0.4],[0.1,4,1.2],[0,1,2]])
    (x,w,b,y) = sess.run((x,w,b,y),feed_dict={x:x_array})
    
    print('x : \n',x)
    print('b : ',b)
    print('w : \n',w)
    print('\ny : ',y)

x : 
 [[0.4 0.2 0.4]
 [0.1 4.  1.2]
 [0.  1.  2. ]]
b :  [[-0.55877167 -1.3260434 ]]
w : 
 [[-0.28018802 -0.075677  ]
 [ 1.7551091  -1.0545963 ]
 [-0.4596087  -0.88853693]]

y :  [[0.        0.       ]
 [5.8821154 0.       ]
 [0.27712   0.       ]]


## <font color='dark'>Simple exercise : using layer

之後我們要建立多層感知層，為方便做調用，可以建立 layer 這個 function 來做使用

In [30]:
def layer(output_dim, input_dim, inputs,activation=None):
    w = tf.Variable(tf.random_normal([input_dim,output_dim]))
    b = tf.Variable(tf.random_normal([1,output_dim]))
    xwb = tf.matmul(inputs,w)+b
    if activation is None:
        output = xwb
    else:
        output = activation(xwb)
    
    return output

In [32]:
# build the input layer 
x = tf.placeholder("float",[None,4])

# build the hidden layer
h = layer(output_dim=3, input_dim=4, inputs=x,activation=tf.nn.relu)

# build the output layer
y = layer(output_dim=2,input_dim=3,inputs=h)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    
    x_array = np.array([[0.4, 0.2, 0.4, 0.5]])
    
    (x,h,y) = sess.run((x,h,y),feed_dict={x:x_array})
    
    print('x : \n',x,'\n')
    print('h : \n',h,'\n')
    print('y : \n',y,'\n')

x : 
 [[0.4 0.2 0.4 0.5]] 

h : 
 [[1.389194  0.8167518 0.       ]] 

y : 
 [[0.8279882 2.4592144]] 

