# Tensorflow Basic

## <font color='dark'>Declaration</font>

### make the constant

In [1]:
import tensorflow as tf
ts_c = tf.constant(2,name='ts_c')
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

### make the variable

In [2]:
ts_x = tf.Variable(ts_c+5,name='ts_x')
ts_x

<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

## <font color='dark'>Excute the computational graph</font>

開啟我們的 Session

In [3]:
sess = tf.Session()

In [4]:
# 起始化所有的 tensorflow global 變數
init = tf.global_variables_initializer()

sess.run(init)

In [5]:
# Way 1

print('ts_c : ',sess.run(ts_c))
print('ts_x : ',sess.run(ts_x))

ts_c :  2
ts_x :  7


In [6]:
# Way 2

print('ts_c : ',ts_c.eval(session=sess))
print('ts_x : ',ts_x.eval(session=sess))

ts_c :  2
ts_x :  7


In [7]:
sess.close()

### You also can use **with** to start the session 

In [8]:
import tensorflow as tf

ts_c = tf.constant(2,name='ts_c')
ts_x = tf.Variable(ts_c+5,name='ts_x')

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('ts_c : ',sess.run(ts_c))
print('ts_x : ',sess.run(ts_x))
sess.close()

ts_c :  2
ts_x :  7


In [9]:
import tensorflow as tf

ts_c = tf.constant(2,name='ts_c')
ts_x = tf.Variable(ts_c+5,name='ts_x')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c : ',sess.run(ts_c))
    print('ts_x : ',sess.run(ts_x))

ts_c :  2
ts_x :  7


## <font color='dark'>Tensorflow placeholder</font>

有時候我們想要用到再指定數值，這時我們就可以使用 placeholder 

In [10]:
width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width,height)

In [11]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area = ',sess.run(area,feed_dict={width:30,height:20}))

area =  600


## <font color="dark">Tensorflow numeric operation</font>

In [12]:
tf_1 = tf.constant(5.0,name='tf_1')
tf_2 = tf.Variable(tf_1+5.0,name='tf_2')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print( 'tf_1 + tf_2 = ',sess.run(tf.add(tf_1,tf_2)) )
    print( 'tf_1 - tf_2 = ',sess.run(tf.subtract(tf_1,tf_2)))
    print( 'tf_1 * tf_2 = ',sess.run(tf.multiply(tf_1,tf_2)))
    print( 'tf_1 / tf_2 = ',sess.run(tf.divide(tf_1,tf_2)))
    print( 'tf_1 / tf_2 餘數 : ',sess.run(tf.mod(tf_1,tf_2)))
    print( 'tf_1 開根號 : ',sess.run(tf.sqrt(tf_1)) )
    print( 'tf_1 絕對值 = ',sess.run(tf.abs(tf_1)) )

tf_1 + tf_2 =  15.0
tf_1 - tf_2 =  -5.0
tf_1 * tf_2 =  50.0
tf_1 / tf_2 =  0.5
tf_1 / tf_2 餘數 :  5.0
tf_1 開根號 :  2.236068
tf_1 絕對值 =  5.0


## <font color='dark'>Tensorboard</font>

In [13]:
# This is a simple tensorflow example

width = tf.placeholder("int32",name='width')
height = tf.placeholder("int32",name='height')
area = tf.multiply(width,height,name='area')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    print("area : ",sess.run(area,feed_dict={width:6,height:8}))

area :  48


In [14]:
# 將寫入的資料做整合
tf.summary.merge_all()
# 將所有的資料寫入 log 檔中，之後我們在打以下指令便可開啟 Tensorboard 看我們的視覺化模型
# tensorboard  --logdir=c:\Users\azaz4\Desktop\tensorflow\log\area  (寫下你的檔案路徑)

train_wirter = tf.summary.FileWriter('log/area',sess.graph)

## <font color='dark'>Make 1D and 2D array by tensorflow</font>

In [15]:
One_D = tf.Variable([0.2, 3, 5.3],name='One_D')

with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    array = sess.run(One_D)
    print(array)
    print("The shape of array : ",array.shape)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[0.2 3.  5.3]
The shape of array :  (3,)


In [16]:
Two_D = tf.Variable([[0,12,41],
                     [13,2,11],
                     [1,67,32]],name='Two_D')

with tf.Session() as sess:
    init = tf.initialize_all_variables()
    sess.run(init)
    array = sess.run(Two_D)
    print(array)
    print("The shape of array : ",array.shape)

[[ 0 12 41]
 [13  2 11]
 [ 1 67 32]]
The shape of array :  (3, 3)


## <font color="dark">Array operation</font>

### multiply

In [17]:
x = tf.Variable([[1.,2.,3.]]) # 1  array 要乘，記得外面多加 [ ] ，這樣 shape 才是 (1,3)
y = tf.Variable([[3,12,5.6],
                 [1.1,2,4],
                 [1,1,0]])

ans = tf.matmul(x,y)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print("Ans = ", sess.run(ans))

Ans =  [[ 8.2 19.  13.6]]


In [18]:
x = tf.Variable([[1.,2.,3.]]) 
y = tf.Variable([[4,5,6],
                 [1.1,2,4],
                 [1,1,0]])

ans = y+x

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print("Ans = ", sess.run(ans))

Ans =  [[5.  7.  9. ]
 [2.1 4.  7. ]
 [2.  3.  3. ]]
