# Numpy 學習筆記

In [1]:
import numpy as np
np.__version__

'1.15.3'

## python - list

### 建立 list

In [3]:
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
L2 = [str(i) for i in L]
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


因為 python 動態型別的特性，可以儲存不同型態的元素

In [5]:
L3 = [True, "I love you", 4, 2.14]
[type(i) for i in L3]

[bool, str, int, float]

但是這樣的彈性造成額外的資源浪費，使整體的效率會降低不少，所以python除了有動態型別的 list，也會有固定型別的 array，在處理陣列會更有效率，在資料型態關於 array 和 numpy 的差別如下圖所示

In [13]:
# jupyte notebook 秀出圖片的方法
from IPython.display import Image
path = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png"
Image(url=path,width = 500)

### 建立 array

In [14]:
import array

In [19]:
L = list(range(10))
A = array.array('i',L)    # 'i' 為指定資料型態， i 代表integer的意思
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Numpy array 基礎 

numpy 的 array 幫助我們更有效率地去處理，幫助我們更有效率地去 **操作處理** data

In [22]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

不同於 python 的 list， np array 所有的元素都須為同個型態，如果型態不符， np 會自動幫你轉換

In [23]:
np.array([3.14, 2, 12])

array([ 3.14,  2.  , 12.  ])

我們也可以明確規定資料形態要哪個類別

In [25]:
np.array([3.14, 2, 12], dtype='i')

array([ 3,  2, 12], dtype=int32)

另外和 list 不同之處在於 np array 可以建立多維度的資料處理

In [27]:
np.array( [range(i,i+3) for i in [1,2,3]] )

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### 從無到有建立 Numpy

In [42]:
# 建立全為 0 或 1 的陣列
zero = np.zeros(10, dtype='i')
one  = np.ones(10,dtype = 'f')

print(f'Zeros:\t{zero}\nOnes:\t{one}\n')

# 建立多維度的陣列 (ex: 3*5)
multiple = np.zeros( (3,5), dtype='i')
print('multiple:\n',multiple)

Zeros:	[0 0 0 0 0 0 0 0 0 0]
Ones:	[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

multiple:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [43]:
# 同是一個數字的陣列
np.full( (3,5), 9453)

array([[9453, 9453, 9453, 9453, 9453],
       [9453, 9453, 9453, 9453, 9453],
       [9453, 9453, 9453, 9453, 9453]])

In [44]:
# 建立一個序列的陣列
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
# 建立一個範圍然後平均飛配的一維陣列
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [50]:
# 亂數建立陣列 (在 0 ~1 的值)
np.random.random((4,4))

array([[0.57808133, 0.00776245, 0.63222343, 0.9910045 ],
       [0.07814415, 0.78945967, 0.90731012, 0.74644756],
       [0.25079362, 0.14875358, 0.92020148, 0.66744196],
       [0.48478722, 0.29081815, 0.06590653, 0.90542071]])

In [54]:
# 亂數建立陣列 (常態分佈法，平均為 0,標準差為 1, 3*3 array)
np.random.normal(0,1,(3,3))

array([[ 0.8493736 , -0.93084468,  0.06805031],
       [-0.95047778, -0.15446123,  1.47224806],
       [ 0.59501407, -0.13356435,  0.78240226]])

In [55]:
# 亂數建立陣列 (限定範圍，ex: 0~10, 3*3)
np.random.randint(0,10,(3,3))

array([[9, 1, 5],
       [6, 5, 2],
       [0, 3, 2]])

In [57]:
# 建立單位矩陣 
np.eye(4,dtype='i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

## Numpy 陣列屬性

In [62]:
x1 = np.random.randint(0,10,size=6)
x2 = np.random.randint(0,10,size=(3,3))
x3 = np.random.randint(0,10,size=(2,3,3))
print(x3)

[[[4 7 3]
  [6 8 8]
  [8 1 9]]

 [[6 8 4]
  [3 7 9]
  [6 3 0]]]


In [65]:
# np array 屬性
print("x3 維度: ",x3.ndim)  # 幾維陣列
print("x3 形狀: ",x3.shape) # 每個維度的大小
print("x3 大小: ",x3.size)  # 所有維度的個數

x3 維度:  3
x3 形狀:  (2, 3, 3)
x3 大小:  18


### 陣列索引

#### 單一索引

numpy array 的索引是從 0 開始計算

In [78]:
a = np.array([i for i in range(10)])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [79]:
print("array 第一個:\t",a[0])
print("array 最後一個:\t",a[-1])

array 第一個:	 0
array 最後一個:	 9


#### 切片索引

切片的輸入方式:   x[start:stop:step]

In [87]:
print("在第5個之前的所有:\t",a[:5])         
print("在第5個之後的所有:\t",a[5:])
print("擷取陣列的片段:\t",a[4:7])
print("擷取片段加間隔:\t",a[4:9:2])
print("\n當間隔為負號時，為往後的間隔\n")
print("反轉所有元素序列:\t",a[::-1])
print("反轉序列加上間隔:\t",a[9::-2])

在第5個之前的所有:	 [0 1 2 3 4]
在第5個之後的所有:	 [5 6 7 8 9]
擷取陣列的片段:	 [4 5 6]
擷取片段加間隔:	 [4 6 8]

當間隔為負號時，為往後的間隔

反轉所有元素序列:	 [9 8 7 6 5 4 3 2 1 0]
反轉序列加上間隔:	 [9 7 5 3 1]


## Numpy 陣列重塑

reshape 可以改變 陣列的型態，但要注意的是型態轉換的尺寸要能夠互相符合 (ex: 3 * 1 --> 1 * 3)

In [130]:
x = np.random.randint(0,10,size=(2,3))
print('Array shape: ',x.shape,'\n')
print(x)

Array shape:  (2, 3) 

[[1 3 6]
 [3 6 2]]


In [131]:
x.reshape((3,2))

array([[1, 3],
       [6, 3],
       [6, 2]])

## Numpy 陣列串接

當你想要把多個陣列合併為一個，或者是想一個陣列分成多個，就看這邊，常用的程序有<font color='red'>np.concatenate</font> , <font color='red'>np.vstack</font> 以及 <font color='red'>np.hstack</font>

我們先來看一下 Numpy 維度上的編號，方便我們理解

In [132]:
# jupyte notebook 秀出圖片的方法
from IPython.display import Image
path = "https://www.python-course.eu/images/axis.jpeg"
Image(url=path,width = 250)

In [133]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

### concatenate

In [134]:
# 一維陣列
np.concatenate( [x,y,z] )

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
# 二維陣列
q = np.arange(6).reshape((2,3))
q

array([[0, 1, 2],
       [3, 4, 5]])

In [136]:
## 沿著第一軸串接  (2 * 3 --> 4*3)
np.concatenate([q,q])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [137]:
## 沿著第二軸串接  (2 * 3 --> 2*6)
np.concatenate([q,q], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## vstack  &  hstack

為了避免在 concatenate 上搞混，vstack(垂直) 和 hstack(水平) 用上來或許會比較直觀

In [138]:
np.vstack([q,q])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [139]:
np.hstack([q,q])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## Numpy 陣列分割

想一個陣列分成多個，就看這邊，常用的程序有<font color='red'>np.split</font> , <font color='red'>np.hsplit</font> 以及 <font color='red'>np.vsplit</font>

N 個分割點 ， 就換產生 N+1 個子陣列 ，看一下下圖會更好了解

In [8]:
from IPython.display import Image
path = "https://i.imgur.com/QoYFyhn.png"
Image(url=path)

In [149]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### split

In [147]:
x1,x2,x3 = np.split(x,[3,6])
print(x1)
print(x2)
print(x3)

[0 1 2]
[3 4 5]
[6 7 8 9]


### vsplit & hsplit 

In [150]:
q = np.arange(16).reshape(4,4)
q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [155]:
q1,q2 = np.vsplit(q,[2])
print(q1,'\n\n',q2)

[[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]


In [156]:
q1,q2 = np.hsplit(q,[2])
print(q1,'\n\n',q2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
